name: MambaQuant_train_x4
model_type: MambaQuantModel
scale: 4
num_gpu: 1
manual_seed: 3407
gpu: 3
bit: 1
cali_data: keydata/cali_data_x4.pdparams
quant:
  hook_per_layer: True
  hook_per_block: False
  qkv_separation: True

quant_conv: True
lora: True
is_finetune: true

# dataset and data loader settings
datasets:
  train:
    task: SR
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: /data1/CKY/Dataset/DF2K/HR
    dataroot_lq: /data1/CKY/Dataset/DF2K/LR_bicubic/X4
    filename_tmpl: "{}x4"
    io_backend:
      type: disk

    gt_size: 256
    use_hflip: True
    use_rot: True

    # data loader
    use_shuffle: True
    num_worker_per_gpu: 16
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda
    pin_memory: True
    num_prefetch_queue: 16

  val_0:
    task: SR
    name: Set5
    type: PairedImageDataset
    dataroot_gt: /data1/CKY/Dataset/SR/Set5/HR
    dataroot_lq: /data1/CKY/Dataset/SR/Set5/LR_bicubic/X4
    filename_tmpl: "{}x4"
    io_backend:
      type: disk

# network structures
network_Q:
  type: MambaIRv2Light
  upscale: 4
  in_chans: 3
  img_size: 64
  img_range: 1.
  embed_dim: 48 
  d_state: 8
  depths: [5, 5, 5, 5]
  num_heads: [4, 4, 4, 4]
  window_size: 16
  inner_rank: 32
  num_tokens: 64
  convffn_kernel_size: 5
  mlp_ratio: 1.0 # 注意这个值也可能需要修改以匹配预训练模型
  upsampler: 'pixelshuffledirect'
  resi_connection: '1conv'

# paths
pathFP:
  pretrain_network_FP: /data1/LWH/MambaIR-main/experiments/pretrained_models/mambairv2_lightSR_x4.pdparams
  strict_load_FP: False

path:
  pretrain_network_Q: /data1/LWH/paddlepaddle_train/experiments/train_paddle_x4_bit2/models/net_Q_11400.pdparams
  strict_load_Q: False

lora_finetune:
  is_train: True # 仍然设置为True，表示该模式下LoRA是激活的
  rank: 8 
  alpha: 16 
  dropout: 0.0

# training settings
train:
  optim_bound:
    type: Adam
    lr: !!float 1e-2
    weight_decay: 0
    beta1:  0.9
    beta2:  0.999

  optim_bit:
    type: Adam
    lr: !!float 1e-3
    weight_decay: 0
    beta1:  0.9
    beta2:  0.999


  scheduler:
    type: MultiStepLR
    milestones: [20000]


  total_iter: 500
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  feature_loss:
    type: MSELoss
    loss_weight: 5
    reduction: mean



# validation settings
val:
  val_freq: !!float 100
  save_img: False

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: True
    
    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 4
      test_y_channel: True

# logging settings
logger:
  print_freq: 10
  save_checkpoint_freq: !!float 100
  use_tb_logger: True
  # wandb:
  #   project: ptq
  #   resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
